//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32941994713271959948248321975648598766826381888897682988942438326656546814128868622345259915532765786412655899591784142183893293614966739916146736263445521794139955622668181383723932139661431249144693976925872511126632178628792332267635339111288933545363532138471222514638578941598198287248279695764321918477877727328812668754697211893318822281465768329213146382213173932564719985981172896326846633552738459839338457217134978117669953677958579652221836687655174542633541111348413346313451115961316827261965747631 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3751	3769	2769	2039	2794	240	3579	1228	4291	220	324	3960	211	1346	237	1586
        ///550	589	538	110	167	567	99	203	524	288	500	111	118	185	505	74
        ///2127	1904	199	221	1201	250	1119	377	1633	1801	2011	1794	394	238	206	680
        ///435	1703	1385	1461	213	1211	192	1553	1580	197	571	195	326	1491	869	1282
        ///109	104	3033	120	652	2752	1822	2518	1289	1053	1397	951	3015	3016	125	1782
        ///2025	1920	1891	99	1057	1909	2237	106	97	920	603	1841	2150	1980	1970	88
        ///1870	170	167	176	306	1909	1825	1709	168	1400	359	817	1678	1718	1594	1552
        ///98	81	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kvvfl kvvfl olud wjqsqa olud frc
        ///slhm rdfm yxb rsobyt rdfm
        ///pib wzfr xyoakcu zoapeze rtdxt rikc jyeps wdyo hawr xyoakcu hawr
        ///ismtq qwoi kzt ktgzoc gnxblp dzfayil ftfx asscba ionxi dzfayil qwoi
        ///dzuhys kfekxe nvdhdtj hzusdy xzhehgc dhtvdnj oxwlvef
        ///gxg qahl aaipx tkmckn hcsuhy jsudcmy kcefhpn kiasaj tkmckn
        ///roan kqnztj edc zpjwb
        ///yzc roc qrygby rsvts nyijgwr xnpqz
        ///jqgj hhgtw tmychia whkm vvxoq tfbzpe ska ldjmvmo
        ///nyeeg omn geyen ngyee rcjt rjuxh
        ///qpq udci tnp fdfk kffd eyzvmg ufppf wfuodj toamfn tkze jzsb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///0
        ///0
        ///1
        ///2
        ///-1
        ///0
        ///-5
        ///-6
        ///-5
        ///-3
        ///-3
        ///-8
        ///-3
        ///-7
        ///-8
        ///-4
        ///-9
        ///1
        ///-3
        ///-17
        ///0
        ///-18
        ///-14
        ///1
        ///-13
        ///-4
        ///-22
        ///-7
        ///-8
        ///-25
        ///-23
        ///-11
        ///-3
        ///-9
        ///-3
        ///-26
        ///-7
        ///-24
        ///-15
        ///-17
        ///2
        ///-18
        ///-39
        ///-6
        ///-28
        ///-27
        ///-38
        ///-47
        ///-17
        ///-16
        ///-36
        ///-34
        ///-3
        ///-40
        ///-11
        ///-45
        ///-11
        ///-34
        ///2
        ///-27
        ///-38
        ///-7
        ///-48
        ///-14
        ///-35
        ///-37
        ///-31
        ///-42
        ///-8
        ///0
        ///-39
        ///-20
        ///-50
        ///-9
        ///-7
        ///-18
        ///-6
        ///-65
        ///-44
        ///-68
        ///-67
        ///-61
        ///-19
        ///-3
        ///0
        ///-66
        ///-63
        ///-29
        ///-4
        ///-29
        ///-77
        ///-51
        ///-72
        ///-91
        ///-84
        ///-38
        ///-93
        ///0
        ///-7
        ///-15
        ///-78
        ///-68
        ///-59
        ///-68
        ///-47
        ///-60
        ///-101
        ///-30
        ///-69
        ///-4
        ///-52
        ///-4
        ///-60
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	5	10	0	11	14	13	4	11	8	8	7	1	4	12	11.
        /// </summary>
        public static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypyemv (1058) -&gt; tdssotr, pebnvks, zaulju
        ///snslv (48)
        ///aytbgf (30)
        ///mkcrsy (42)
        ///shwcd (42)
        ///muwcoy (63)
        ///dabfreg (49)
        ///iblvv (68)
        ///qqircn (401)
        ///pwpnfx (67)
        ///tlnztuz (60)
        ///ctglahh (17)
        ///pjkgn (170) -&gt; pstttg, xdkoxrg, cvuvxi
        ///ulasjv (114) -&gt; tkeney, zaffbku
        ///ojoim (139) -&gt; obebr, zxwlsj
        ///vhxxnj (109) -&gt; ooaouu, vraxbmd
        ///blbjzdr (40)
        ///iuctosc (12) -&gt; bqmayvq, yjzvbcb, takuy, qlsfhyp
        ///mfafdfn (73)
        ///egfrye (72) -&gt; uwxizpk, igbamrm
        ///cqokt (1487) -&gt; sjmfsib, ubspq, wsaugv
        ///ekorcyg (67)
        ///sfyxd (83)
        ///trkiub (65) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n dec 271 if az &lt; 3
        ///f inc -978 if nm &lt;= 9
        ///g inc -336 if ga &lt; 2
        ///egk dec 437 if y &lt; 5
        ///z dec -550 if g == -336
        ///mx dec 12 if bqr == 0
        ///mx dec 433 if ns == 0
        ///ic inc 506 if g &lt;= -327
        ///ga dec -560 if ic != 506
        ///bqr dec 570 if az &gt;= -9
        ///g dec 372 if egk != -429
        ///f dec -863 if b &gt;= -9
        ///gyc inc 844 if av &gt;= 7
        ///cr inc -781 if mx &gt;= -453
        ///ga dec 346 if cr == -781
        ///b inc -162 if z &lt; 554
        ///nno inc 504 if g &lt;= -700
        ///mx dec -32 if vkg &lt;= 6
        ///mx dec -961 if nno &lt; 509
        ///az dec 320 if ic &lt; 510
        ///nm dec 594 if ga != -354
        ///cr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n,nw,nw,sw,s,sw,sw,s,s,s,s,s,ne,s,ne,se,se,sw,s,se,se,se,n,se,se,ne,se,ne,n,ne,ne,sw,ne,ne,se,ne,ne,ne,sw,ne,ne,ne,n,ne,n,n,se,ne,ne,n,sw,n,ne,n,ne,n,ne,n,n,n,n,n,n,n,ne,n,n,sw,nw,n,nw,n,nw,n,n,nw,s,nw,nw,n,n,nw,se,nw,nw,sw,n,n,n,nw,nw,n,nw,nw,nw,nw,nw,ne,nw,nw,nw,sw,sw,nw,nw,nw,ne,sw,se,n,s,nw,sw,nw,s,sw,sw,n,nw,sw,sw,nw,sw,sw,nw,nw,nw,sw,sw,sw,s,sw,se,sw,sw,ne,sw,sw,sw,ne,sw,sw,sw,nw,sw,sw,sw,sw,sw,nw,sw,se,se,nw,nw,sw,sw,sw,ne,nw,sw,n,sw,sw,sw,sw,se,sw,sw,se,sw,ne,nw,sw,sw,nw,sw,sw,sw,se,sw,s,s,s,sw,s,sw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
    }
}
